language: node_js
node_js:
  - "8.11.3"
cache:
  - directories:
    - node_modules
os:
  - osx
  - linux

jobs:
  include:
    - stage: test
      name: "Web Production build"
      script:
        - npm install
        - npm run build
    - stage: test
      name: "Desktop (all) build"
      script:
        - npm install
        - npm run build-desktop
    - stage: test
      name: "Windows build"
      script:
        - npm install
        - npm run build
        - npm run build-desktop-win
    - stage: test
      name: "macOS (all) build"
      if: os = osx
      script:
        - npm install
        - npm run build
        - npm run build-desktop-macos
    - stage: test
      name: "Linux (all) build"
      script:
        - npm install
        - npm run build
        - npm run build-desktop