jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: .azure/setup.yml
    - template: .azure/build-web.yml
    - script: |
        npm run build-desktop-linux
    displayName: 'Build Linux client'

  - job: macOS
    pool:
      vmImage: 'mac-latest'
    steps:
    - template: .azure/setup.yml
    - template: .azure/build-web.yml
    - script: |
        npm run build-desktop-macos
    displayName: 'Build macOS client'

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - template: .azure/setup.yml
    - template: .azure/build-web.yml
    - script: |
        npm run build-desktop-win
    displayName: 'Build Windows client'