name: Build macOS Client

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run pre-build setup
        run: |
          echo "$ascCertificates" > certs.b64
          base64 --decode certs.b64 > Certificates.p12
          security add-generic-password -a "appleseed@marquiskurt.net" -w "$ascPassword" -s "AC_PASSWORD"
          security import Certificates.p12 -P "$ascCertsPassword" -k /Library/Keychains/System.keychain
        env:
          ascPassword: ${{ secrets.ASC_PASSWORD }}
          ascCertificates: ${{ secrets.ASC_CERTS }}
          ascCertsPassword: ${{ secrets.ASC_CERTS_PASSWORD }}
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run build-desktop-darwin-nosign